name: mortpipe

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - pandas
  - numpy 
  - matplotlib
  - jupyter
  - notebook
  - scipy
  - scikit-learn
  - imbalanced-learn
  - pytorch
  - torchvision